// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("phoneNumbers")
                        .HasColumnType("TEXT");

                    b.Property<string>("surname")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            id = 1,
                            firstName = "Pawel",
                            phoneNumbers = "502689909",
                            surname = "Labuz"
                        },
                        new
                        {
                            id = 2,
                            firstName = "Jan",
                            phoneNumbers = "702689909",
                            surname = "Kowalski"
                        },
                        new
                        {
                            id = 3,
                            firstName = "Adam",
                            phoneNumbers = "802689909",
                            surname = "Malysz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
